gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Rayana Verissmo
description: Portfolio

# Name of project on Github
baseurl: /

# Build settings
markdown: kramdown
